#!/bin/bash
#
today=$(date +"%Y-%m-%d")
file="$SECOND_BRAIN"'/periodic-notes/thoughts/'$1'_'$(date +"%Y-%m-%d").md
echo "$file"
cd "$SECOND_BRAIN" || exit

new_note() {
	touch "$file"

	# Format the file with the daily template
	cat <<EOF >"$file"
---
tags:
    - $1
    - 
---
# $1 $today

## Intention (brief motivation)

## What is the new idea?

## Tracking

- [ ] Work on PhD
- [ ] Work on EJ
- [ ] Work on own project

## describe more
EOF

}

# If the daily note does not exist, create a new one.
# this uses the test command with the -f flag.
if [ ! -f "$file" ]; then
	echo "File does not exist, creating new daily note."
	new_note
fi

# Open the daily note at the bottom of the file in insert mode
nvim '+ normal Gzzo' "$file"
# Open the daily note at the bottom of the file in insert mode and run NoNeckPain to make it center
# nvim '+ normal Gzzo' "$file" -c :NoNeckPain
